# "step re-use" template to do something with Docker to every image.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

parameters:
  command: build

steps:
  # OpenXR spec builder
  - template: build-template.yml
    parameters:
      command: ${{ parameters.command }}
      repo: openxr-base
      version: 202110

  - template: build-template.yml
    parameters:
      command: ${{ parameters.command }}
      repo: openxr
      version: 202110

  # OpenXR SDK builder
  - template: build-template.yml
    parameters:
      command: ${{ parameters.command }}
      repo: openxr-sdk
      version: 202110

  - template: build-template.yml
    parameters:
      command: ${{ parameters.command }}
      repo: openxr-pregenerated-sdk
      version: 202201

  # Rust bindings-generator builder
  - template: build-template.yml
    parameters:
      command: ${{ parameters.command }}
      repo: rust
      version: 202206
