# Main azure-pipelines config file

jobs:
  # "build" job - run on all branches
  - job: build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: all-images.yml
        parameters:
          command: build
