# "step re-use" template to execute a docker command step in this repo with minimum params,
# based on the structure of this repo.
# See <https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops>

parameters:
  imageName: "khronosgroup/docker-images"
  tag:
  command: build
  version:

steps:
  - task: Docker@2
    displayName: ${{ parameters.command }} ${{ parameters.tag }} ${{ parameters.version }}
    inputs:
      repository: ${{ parameters.imageName }}
      command: ${{ parameters.command }}
      arguments: "--build-arg \"VERSION=${{ parameters.version }}\""
      tags: |
        ${{ parameters.tag }}.latest
        ${{ parameters.tag }}.${{ parameters.version }}
      Dockerfile: ${{ parameters.tag }}.Dockerfile
